# Generated by Django 4.2.5 on 2023-10-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceswap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='face_Main_Img',
        ),
    ]
