# Generated by Django 4.2.5 on 2023-10-09 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faceswap', '0002_rename_hotel_main_img_hotel_face_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cartoon_Main_Img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
